name: Node.js Vite CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: 25.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v4
      with:
        path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy Github Pages
      id: deployment
      uses: actions/deploy-pages@v4
